Add repro for failing typegen with Uuid
For counter app, typegen now fails with this error, because a Uuid is
included in an Event enum case

  thread 'main' panicked at 'type registration failed: type tracing failed: Failed to deserialize value: "UUID parsing failed: invalid length: expected 16 bytes, found 0"', shared_types/build.rs:12:30
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace